name: adbnerve
description: Android toolkit for Flutter
version: 0.2.5
homepage: https://github.com/sharpordie/adbnerve
publish_to: none

environment:
  # sdk: '>=2.18.4 <3.0.0'
  sdk: ">=3.0.2 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  adbready:
    git: https://github.com/sharpordie/adbready
  archive: ^3.3.7
  dio: ^5.1.2
  flutter:
    sdk: flutter
  format: ^1.3.0
  google_mlkit_text_recognition: ^0.6.0
  path: ^1.8.3
  path_provider: ^2.0.15
  path_provider_platform_interface: ^2.0.6
  plugin_platform_interface: ^2.1.4
  uuid: ^3.0.7
  xml: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

# dependency_overrides:
#   meta: ^1.9.0

flutter:
