name: adbnerve
description: Android toolkit for Flutter
version: 0.3.2
homepage: https://github.com/sharpordie/adbnerve
publish_to: none

environment:
  sdk: ^3.5.4
  flutter: '>=3.3.0'

dependencies:
  adbready:
    git: https://github.com/sharpordie/adbready
  archive: ^4.0.0
  dio: ^5.7.0
  flutter:
    sdk: flutter
  format: ^1.5.2
  google_mlkit_text_recognition: ^0.14.0
  path: ^1.9.0
  path_provider: ^2.1.5
  path_provider_platform_interface: ^2.1.2
  plugin_platform_interface: ^2.1.8
  uuid: ^4.5.1
  xml: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
