name: adbnerve
description: Android toolkit for Flutter
version: 0.1.2
homepage: https://github.com/sharpordie/adbnerve

environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  adbready:
    git: https://github.com/sharpordie/adbready
  archive: ^3.3.4
  dio: ^4.0.6
  flutter:
    sdk: flutter
  path: ^1.8.2
  path_provider: ^2.0.11
  path_provider_platform_interface: ^2.0.5
  plugin_platform_interface: ^2.1.3
  xpath_selector: ^3.0.1
  xpath_selector_xml_parser: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
