name: adbnerve
description: Android toolkit for Flutter
version: 0.2.8
homepage: https://github.com/sharpordie/adbnerve
publish_to: none

environment:
  sdk: ">=3.0.2 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  adbready:
    git: https://github.com/sharpordie/adbready
  archive: ^3.4.9
  dio: ^5.4.0
  flutter:
    sdk: flutter
  format: ^1.4.0
  google_mlkit_text_recognition: ^0.11.0
  path: ^1.8.3
  path_provider: ^2.1.1
  path_provider_platform_interface: ^2.1.1
  plugin_platform_interface: ^2.1.7
  uuid: ^4.2.2
  xml: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

# dependency_overrides:
#   meta: ^1.9.0

flutter:
